// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetBoard() {
  return window['go']['main']['App']['GetBoard']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Restart() {
  return window['go']['main']['App']['Restart']();
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetConciseMode(arg1) {
  return window['go']['main']['App']['SetConciseMode'](arg1);
}

export function SetHideDone(arg1) {
  return window['go']['main']['App']['SetHideDone'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetViewMode(arg1) {
  return window['go']['main']['App']['SetViewMode'](arg1);
}

export function ShowWaterReminder() {
  return window['go']['main']['App']['ShowWaterReminder']();
}

export function UpsertGroup(arg1, arg2) {
  return window['go']['main']['App']['UpsertGroup'](arg1, arg2);
}

export function UpsertTask(arg1) {
  return window['go']['main']['App']['UpsertTask'](arg1);
}
