// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {version} from '../models';
import {todo} from '../models';

export function CheckUpdate():Promise<version.UpdateCheckResult>;

export function DeleteGroup(arg1:number):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetBoard():Promise<todo.Board>;

export function GetVersion():Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function Restart():Promise<void>;

export function SetAlwaysOnTop(arg1:boolean):Promise<todo.Settings>;

export function SetConciseMode(arg1:boolean):Promise<todo.Settings>;

export function SetHideDone(arg1:boolean):Promise<todo.Settings>;

export function SetViewMode(arg1:string):Promise<todo.Settings>;

export function ShowWaterReminder():Promise<void>;

export function UpsertGroup(arg1:number,arg2:string):Promise<todo.Group>;

export function UpsertTask(arg1:todo.Task):Promise<todo.Task>;
